version: '3'

services:
  import:
    build:
      context: .
    volumes:
      - ./:/usr/src
    entrypoint:
      - "/bin/sh"
    environment:
      - PANOPTES_CLIENT_SECRET=<PANOPTES_CLIENT_SECRET>
      - LASAIR_TOKEN=<LASAIR_TOKEN>
